= 週末旅行日誌！ 北インド編１ - #インド旅行っぽさとは

さて、
https://stay-india.github.io/2015/10/21/go_to_north_india.html/?prev[前の記事で]堂々宣言した北インド旅行。 +
ホテルにチェックインしたあとでで本日の振り返りブログを書いてました！

木曜からの連休に合わせてということで水曜日の22:20のフライトに乗る予定。 +
2時間30分くらいで着くとかそんなあいまいな記憶。 +
だいたい1時間30分前に着けばよいかなと思い、空港までは1時間程度なので19:45とかそのくらいの時間にタクシーを呼んだ。

*「オーケーオーケー！ツーミニッツ！」*

どうやらあと2分で来るらしい。 +
流石にインドで有名なタクシー手配アプリは優秀だなあ。

ってね。 +
ってね。 +
常々思っていて +
本当に便利 +
すばらしい +
ツーミニッツでね +
来るんだもの！

== 20分以上待った(現実)

*あー、これなんかインド旅行っぽーい。* +
とか言ってる場合じゃなくてな？

そして運転中。 +
*「ツーミニッツ！！」*

なんだその突然の*2分*は？ +
と思ったらガソリン入れだしたんですね。 +
割とインドのタクシーって客がいても平気でガソリン入れだすんですね。 +
常にキープしとく精神とか皆無なので。

*あー、これなんかインド旅行っぽーい。* +
とか言ってる場合じゃなくてな？

でね。途中ちょっと渋滞が激しい。 +
ああ、早くしてくれないかなーって思ったら。 +
見事に会社の近くのマクドナルドが見えた。

うん。その通り。 +
そのマクドナルドは*家から空港までの直線上からかけ離れている*のである。

あ、やべー。これもしかして割と*ハズレ*の方じゃない？ +
そうなんですね。 +
インドのタクシーの運転手って本当に道に詳しく *ない*んですよ！ +
うちの周辺でタクシー拾うと基本的に私の方が詳しいくらいです。 +
というかまずたいてい*Google Maps見てる私の方が詳しい*というか*あいつら地図の見方がわかってないんじゃないか？*というレベルです。

ということでGoogle Mapsを見たんですけど、やっぱりまあ *遠回り*してるわけですわな。

*あー、これなんかインド旅行っぽーい。* +
とか言ってる場合じゃなくてな？

マップ見て指示出そうと思っていたら*悪夢のSIMが認識されない問題が再発*。 +
Map見れない。 +
渋滞がひどいなかカチカチいろいろと操作してなんとか復活。

マップを見た。

そこに見えた文字。

=== マジェスティック

説明しよう、マジェスティックとはバンガロールの中心駅であり、どれくらい中心かというと電車の駅だけでなくバスの駅もそこにはあるため、すごく簡単に言うと*連休の前の夜行バス乗り場とか電車の駅の周辺とか誰がどう考えたって混雑してるに決まってんだろうが！！サルでもわかるってやつだろうが！！！！* +
ってことです。

まあおおよそ推測するに*「道に自信がないから一度マジェスティックに出よう！」*くらいの考えだったんでしょう。このドライバーの感じね。

*あー、これなんかインド旅行っぽーい。* +
とか言ってる場合じゃなくてな？

なんやねん状態ですよ。焦る。さすがに焦る。 +
だいじょうぶかな？だいじょうぶかな？

=== 「ンンー、ベリ〜ヘヴィ〜トラフィックジャ〜ムウ〜」

そこで突然のドライバーの発言がこれな。 +
ん？この周辺で一番混みそうな道を選んだ初心者ドライバーみたいなやつはどこの誰だと思っとるんや？ +
そしてともだちからかかってきたっぽい電話に何やら不満みたいなことを言ってる場合か？ん？ +
やれ空港が遠いとか渋滞がどうとかその手の話。 +
こっちがヒンドゥー語をわからないことに言いたい放題というかもうずっと話してる。 +
なんでヒンドゥー語がわかるかって？ +
*ヒンドゥー語と英語の区別がつかない*奇跡の人間がときおり見受けられて、彼もそのひとりだったので、英語が混じって聞こえるんですわ。

*あー、これなんかインド旅行っぽーい。* +
とか言ってる場合じゃなくてな？

急げや！ということで、結局道が広く渋滞が解消されてからは急がせました。 +
遠回りとか渋滞に捕まったとかで結局962ルピーとか前に使ったときとの比較で *3倍くらいの額*を請求されましたが、急いでいたので1000ルピー渡して「釣りは取っとけ！」と走りました。

急いで入って聞きました。

22:20のフライトに乗りたいんだが！？

どこへ行けばいい？？

== 「クローズしてます。」

( ﾟдﾟ)

*( ﾟдﾟ)*

*生まれーてーはーじめーて♪* +
*フライートのーがしーたー♫* +
*フォーザーファースタイムインフォーエーヴァアアアアァァァァ！！*

はっ、テンパッて *アナ雪のあの曲*を替え歌にしてる場合じゃない！ +
何より自分と神田沙也加の共通点が *日本人*という点以外まったく思いつかないから本当にそんな歌ってる場合じゃない！

video::8_Cm5bjsNE8[youtube]


乗り遅れたことに関しては着いたのは21:55だったからそれはそうだなという感じである。 +
ふつうにチケット交換してもらいました。 +
ただなぜかチケットの支払いが完了していないので、新規の購入ですって言われてとにかく確認しないとダブって2重請求されている可能性あるのでそこらへんはあとで確認しなきゃですね。 +
次は2時間前に着くようにすればよいのだろうか？悩ましいですね。 +

まあ冷静にポストポーン的な感じで翌日のチケットを手に入れたから思ったのですが。

== 北インドなんてロクなところじゃねえから行くんじゃない！というメッセージなのでは？

まあ手に入れちゃった以上は乗るつもりですけどね。

そういえば冒頭でホテルにチェックインしたと言ったな？ +
あれはデリーでじゃない！ +
*バンガロールでだ！*

バンガロールの空港でOne Day Hotelに泊まったお話に続きます。
